ASoC: Intel: skl_hda_dsp_generic: fix clang/gcc build error
Use semicolon to complete an expression instead of comma for following
build error.

sound/soc/intel/boards/skl_hda_dsp_generic.c:108:2: error: expected expression
        dev_dbg(&pdev->dev, "board_quirk = %lx\n", board_quirk);

Cc: stable@vger.kernel.org
Fixes: 33e59e50ee76 ("ASoC: Intel: skl_hda_dsp_generic: Allocate snd_soc_card dynamically")
Signed-off-by: Brent Lu <brent.lu@intel.com>